apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemm-kernel-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemm-kernel-visualizer
  template:
    metadata:
      labels:
        app: gemm-kernel-visualizer
    spec:
      containers:
      - name: gemm-kernel-visualizer
        image: your-docker-registry/gemm-kernel-visualizer:latest
        ports:
        - containerPort: 8050
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gemm-kernel-visualizer-service
spec:
  selector:
    app: gemm-kernel-visualizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: LoadBalancer
